### ISSUE TITLE
"By Stars" category is far from accurate

### ISSUE THREAD

**Issue by freedomofkeima** [antonybudianto/go-github#10]
Hi,

First of all, I want to say that GitCard is a nice work 👏

I only want to point out that "By Stars" logic is a bit far from accurate.

https://github.com/antonybudianto/go-github/blob/f8462b6a7cfdb58b94801274aba5a1d195d5c287/github/github_query.go#L100-L107

For example, from [git-awards.com](http://git-awards.com/users?utf8=%E2%9C%93&type=country&language=javascript&country=Indonesia), we can see that the top 4 persons are not included in the calculation since their followers are `189`, `197`, `146`, and `229` respectively. Current logic seems to only handle users who have more than `260` followers (Rank 25).

![stars](https://user-images.githubusercontent.com/2115470/67098809-cec8e800-f1f7-11e9-94f9-8fc361f38266.png)

One way to fix it while keeping under the rate limit is to increase the number of followers and increase number of records that we want to retrieve. For the reference (as of today), in Indonesia:
- There are `90` people with followers more than `125`
- There are `69` people with followers more than `150`
- There are `43` people with followers more than `200`

Keep up the good work!

**Comment by antonybudianto** [comment]
Hi, thanks for pointing out. I’ve known this issue, and decided to go with 200 follower standard, since it’s very heavy to fetch all of the dev’s repo (1 dev can have multiple repo fetch if >= 100 repo). I might update the standard after a while
